/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servicejuridique.vues;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import servicejuridique.sources.DateConvention;
import servicejuridique.sources.Diplome;
import servicejuridique.sources.Etudiant;
import servicejuridique.sources.PreConvention;

/**
 *
 * @author marieroca
 */
public class ListePreConv extends javax.swing.JFrame {
    private HashMap<Long, PreConvention> conv;

    /**
     * Creates new form Juridique
     */
    public ListePreConv() {
        initComponents();
        
        conv = new HashMap();
        Diplome d = new Diplome(1L, Diplome.Niveau.M2, "MIAGE");
        Etudiant e1 = new Etudiant(1L, "Murillo--Cantié", "Emma", "MAIF", "maif1", d);
        Etudiant e2 = new Etudiant(2L, "Pasero", "Hugo", "MAIF", "maif2", d);
        Etudiant e3 = new Etudiant(3L, "Roca", "Marie", "MAAF", "maaf1", d);
        
        try {
            PreConvention p1 = new PreConvention(1L, new DateConvention("01/06/2018"), new DateConvention("31/08/2018"), 1200.0F, "Chargé d'affaire", "Sharepoint", "ENEDIS GRDF", "François Guiraud", "ERDF1234", e1);
            PreConvention p2 = new PreConvention(2L, new DateConvention("01/06/2018"), new DateConvention("31/08/2018"), 1100.0F, "Développeur", "Web", "Banque populaire", "M. Jean-Claude", "BP1234", e2);
            PreConvention p3 = new PreConvention(3L, new DateConvention("01/06/2016"), new DateConvention("31/08/2018"), 1150.0F, "Assistance MOA", "Tuleap", "Orange", "Aurélie", "O1234", e3);
            conv.put(p1.getId(),p1);
            //System.out.print(p1.getId());
            conv.put(p2.getId(),p2);
            //System.out.print(p2.getId());
            conv.put(p3.getId(),p3);
            //System.out.print(p3.getId());
        } catch (ParseException ex) {
            Logger.getLogger(ListePreConv.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //ArrayList<PreConvention> pc = new ArrayList(conv.values());

        ((DefaultTableModel) this.tabAValider.getModel()).setRowCount(conv.size());
        
        this.tabAValider.getColumn(tabAValider.getColumnName(0)).setMinWidth(45);
        this.tabAValider.getColumn(tabAValider.getColumnName(0)).setMaxWidth(60);
        
        int i = 0;
        for(PreConvention c : conv.values()){
            this.tabAValider.setValueAt(c.getId(), i, 0);
            this.tabAValider.setValueAt(c.getEtudiant().getNom(), i, 1);
            this.tabAValider.setValueAt(c.getEtudiant().getPrenom(), i, 2);
            this.tabAValider.setValueAt(c.getEntreprise(), i, 3);
            i++;
        }   
    }

    public HashMap<Long, PreConvention> getConv() {
        return conv;
    }

    public void setConv(HashMap<Long, PreConvention> conv) {
        this.conv = conv;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puSelectionUnique = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        bPuOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tabNavigation = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        bOuvrirRefusees = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabAValider = new javax.swing.JTable();

        puSelectionUnique.setTitle("Selection");

        jLabel2.setText("Vous devez sélectionner qu'un seul élément");

        bPuOk.setText("OK");

        javax.swing.GroupLayout puSelectionUniqueLayout = new javax.swing.GroupLayout(puSelectionUnique.getContentPane());
        puSelectionUnique.getContentPane().setLayout(puSelectionUniqueLayout);
        puSelectionUniqueLayout.setHorizontalGroup(
            puSelectionUniqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puSelectionUniqueLayout.createSequentialGroup()
                .addGroup(puSelectionUniqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puSelectionUniqueLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(puSelectionUniqueLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(bPuOk)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        puSelectionUniqueLayout.setVerticalGroup(
            puSelectionUniqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puSelectionUniqueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPuOk))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Liste des pré-conventions à valider :");

        tabNavigation.setToolTipText("");
        tabNavigation.setName(""); // NOI18N

        bOuvrirRefusees.setText("Ouvrir");
        bOuvrirRefusees.setActionCommand("bOuvrir");
        bOuvrirRefusees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bOuvrirRefuseesMouseClicked(evt);
            }
        });
        bOuvrirRefusees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOuvrirRefuseesActionPerformed(evt);
            }
        });

        tabAValider.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Prénom", "Entreprise"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tabAValider);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 299, Short.MAX_VALUE)
                .addComponent(bOuvrirRefusees))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bOuvrirRefusees))
        );

        tabNavigation.addTab("Refusées", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(tabNavigation)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabNavigation))
        );

        tabNavigation.getAccessibleContext().setAccessibleName("AValider");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOuvrirRefuseesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOuvrirRefuseesActionPerformed
        int[] lignes = tabAValider.getSelectedRows();
        //on ne peut modifier qu'une seule ligne
        //on teste donc combien de lignes sont sélectionnées et on retourne une pop-up d'info
        //si plusieurs le sont
        if(lignes.length > 1){
            this.puSelectionUnique.setVisible(true);
        } else {
            PreConvention con = (PreConvention) tabAValider.getValueAt(tabAValider.getSelectedRow(),0);
            Long key = (Long) tabAValider.getValueAt(tabAValider.getSelectedRow(), 0);
            PreConvention pc = conv.get(key);
            DetailsPreConv fen = new DetailsPreConv(this, key);
            fen.setVisible(true);
        }
    }//GEN-LAST:event_bOuvrirRefuseesActionPerformed

    private void bOuvrirRefuseesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOuvrirRefuseesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bOuvrirRefuseesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListePreConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListePreConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListePreConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListePreConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListePreConv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOuvrirRefusees;
    private javax.swing.JButton bPuOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JDialog puSelectionUnique;
    private javax.swing.JTable tabAValider;
    private javax.swing.JTabbedPane tabNavigation;
    // End of variables declaration//GEN-END:variables
}
